version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: 'db'
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "picpay"
      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/db:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'app'
    ports:
      - 8000:8000
    volumes:
#      - ./:/var/www/html
      - ./:/app
#    depends_on:
#      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge

